workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "podsan"'

build:
  tags:
    - podman-deploy
  script:
    - |
      : "${EDS_IMAGE_PREFIX:?EDS_IMAGE_PREFIX is required}"
      export IMAGE_SHA="localhost/${EDS_IMAGE_PREFIX}-calrs:podsan-${CI_COMMIT_SHORT_SHA}"
      export IMAGE_BRANCH="localhost/${EDS_IMAGE_PREFIX}-calrs:podsan"
    - |
      docker build \
        --build-arg EDS_IMAGE_PREFIX \
        --build-arg HTTP_PROXY \
        --build-arg HTTPS_PROXY \
        --build-arg NO_PROXY \
        --build-arg http_proxy \
        --build-arg https_proxy \
        --build-arg no_proxy \
        --label "org.opencontainers.image.revision=$CI_COMMIT_SHA" \
        --tag "$IMAGE_SHA" \
        --tag "$IMAGE_BRANCH" \
        .
    - docker image inspect "$IMAGE_SHA" >/dev/null
    - docker image inspect "$IMAGE_BRANCH" >/dev/null
